<a href="https://colab.research.google.com/github/RiteshDKgpian/X-tra-Telegram/blob/master/Final_Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Train_Data_Health.csv')
df

ID1  Specific ailments    ID2 Food preference  Age        BMI  \
0       2408                 44   2668             DX6   49  20.500470   
1      25063                 39  10363        DX3 DX4    20  26.076580   
2      26798                 29    132             DX6    1  21.420866   
3      31907                 27  10499            DX1    30  25.203247   
4      26412                  9   7963             DX6   40  19.355846   
...      ...                ...    ...             ...  ...        ...   
25915     69                 12    818             DX6   58  25.515286   
25916  21001                 39  11500             DX6   16  27.094959   
25917   4263                 44   2796            DX1     8  28.602921   
25918  11208                 52  12190            DX1    52  21.909832   
25919  21535                 17   8324            DX4    41  23.828813   

      Smoker? Living in? Any heriditary condition?  Follow Diet  \
0          NO      RURAL                    Stable          1.0   
1          NO      URBAN                    Stable          0.0   
2          NO      URBAN                    Stable          1.0   
3          NO      RURAL                    Stable          1.0   
4         YES      RURAL                    Stable          1.0   
...       ...        ...                       ...          ...   
25915     YES      RURAL                    Stable          1.0   
25916      NO      RURAL                    Stable          1.0   
25917      NO      RURAL                    Stable          1.0   
25918      NO      RURAL                    Stable          0.0   
25919      NO      RURAL                    Stable          1.0   

       Physical activity  Regular sleeping hours  Alcohol consumption  \
0                    0.0                     0.0                  0.0   
1                    0.0                     0.0                  0.0   
2                    0.0                     0.0                  0.0   
3                    0.0                     0.0                  0.0   
4                    0.0                     0.0                  0.0   
...                  ...                     ...                  ...   
25915                0.0                     0.0                  0.0   
25916                0.0                     0.0                  0.0   
25917                1.0                     0.0                  0.0   
25918                1.0                     0.0                  1.0   
25919                0.0                     0.0                  0.0   

       Social interaction  Taking supplements  Mental health management  \
0                     0.0                 0.0                       0.0   
1                     1.0                 0.0                       0.0   
2                     0.0                 0.0                       0.0   
3                     0.0                 0.0                       0.0   
4                     1.0                 0.0                       0.0   
...                   ...                 ...                       ...   
25915                 0.0                 0.0                       0.0   
25916                 0.0                 0.0                       0.0   
25917                 0.0                 0.0                       0.0   
25918                 0.0                 0.0                       0.0   
25919                 0.0                 0.0                       0.0   

       Illness count last year  Healthy  
0                          1.0        1  
1                          1.0        1  
2                          1.0        0  
3                          1.0        1  
4                          2.0        1  
...                        ...      ...  
25915                      1.0        1  
25916                      1.0        0  
25917                      2.0        1  
25918                      2.0        1  
25919                      1.0        1  

[25920 rows x 18 columns]

In [ ]:
df['Food preference'].value_counts()

DX6                     9639
DX5                     2167
DX2                     2128
DX4                     2099
DX3                     2072
DX1                     2063
DX1 DX2                  480
DX2 DX4                  476
DX3 DX4                  471
DX1 DX3                  461
DX4 DX5                  459
DX2 DX5                  459
DX2 DX3                  452
DX1 DX5                  450
DX3 DX5                  443
DX1 DX4                  437
DX1 DX2 DX5              116
DX1 DX3 DX4              113
DX1 DX2 DX3              110
DX1 DX2 DX4              110
DX3 DX4 DX5              109
DX2 DX3 DX5              105
DX1 DX3 DX5               98
DX2 DX4 DX5               98
DX2 DX3 DX4               90
DX1 DX4 DX5               89
DX1 DX3 DX4 DX5           27
DX2 DX3 DX4 DX5           26
DX1 DX2 DX4 DX5           23
DX1 DX2 DX3 DX4           20
DX1 DX2 DX3 DX5           16
DX1 DX2 DX3 DX4 DX5        4
Name: Food preference, dtype: int64

In [ ]:
df = df.drop(['Food preference'], axis =1)

In [ ]:
df.isna().sum()

ID1                            0
Specific ailments              0
ID2                            0
Age                            0
BMI                            0
Smoker?                        0
Living in?                     0
Any heriditary condition?      0
Follow Diet                  973
Physical activity            973
Regular sleeping hours       973
Alcohol consumption          973
Social interaction           973
Taking supplements           973
Mental health management     973
Illness count last year      973
Healthy                        0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
X = df.drop(['Healthy'], axis = 1)
y = df['Healthy']

In [ ]:
# lbl = LabelEncoder()
# X = X.drop(['ID1'], axis = 1, inplace = True)
# X = X.drop(['ID2'], axis = 1, inplace = True)

X = X.apply(LabelEncoder().fit_transform)

In [ ]:
X.value_counts()
# X_train['Food preference'].value_counts()

ID1    Specific ailments  ID2    Age  BMI    Smoker?  Living in?  Any heriditary condition?  Follow Diet  Physical activity  Regular sleeping hours  Alcohol consumption  Social interaction  Taking supplements  Mental health management  Illness count last year
0      1                  4636   27   8198   2        0           0                          0            0                  1                       0                    0                   0                   0                         0                          1
17277  41                 363    4    793    1        0           0                          1            0                  0                       0                    0                   0                   0                         0                          1
17287  1                  10418  25   1089   2        0           0                          1            0                  0                       0                    0                   0                   

In [ ]:
X.isna().sum()

ID1                          0
Specific ailments            0
ID2                          0
Age                          0
BMI                          0
Smoker?                      0
Living in?                   0
Any heriditary condition?    0
Follow Diet                  0
Physical activity            0
Regular sleeping hours       0
Alcohol consumption          0
Social interaction           0
Taking supplements           0
Mental health management     0
Illness count last year      0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn import preprocessing

In [ ]:
def score(model, title = "Default"):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    # print(confusion_matrix(y_test, preds))
    accuracy = round(accuracy_score(y_test, preds), 5)
    print('Accuracy for', title, ':', accuracy, '\n')
    return preds

In [ ]:
lg = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
score(lg, "Logistic Regression")

Accuracy for Logistic Regression : 0.62579 



array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
ada = AdaBoostClassifier(n_estimators=1000,random_state=0)
score(ada, "AdaBoostClassifier")

Accuracy for AdaBoostClassifier : 0.76841 



array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
rdf = RandomForestClassifier(n_estimators=1000,max_depth=10,random_state=0)
score(rdf,'RandomForestClassifier')

Accuracy for RandomForestClassifier : 0.78104 



array([0, 0, 1, ..., 1, 1, 1])

In [ ]:
x_tes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Test_Data_Health.csv')

In [ ]:
x_tes = x_tes.apply(LabelEncoder().fit_transform)
x_tes = x_tes.drop(['Food preference'], axis =1)

In [ ]:
pred = rdf.predict(x_tes)

In [ ]:
res_rdf = pd.DataFrame(pred)

In [ ]:
res_rdf.to_csv('res_rdf.csv', index=False)

In [ ]:
nb = GaussianNB()
score(nb,'GaussianNB without hyperparameter tuning')

params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gs_NB = GridSearchCV(estimator=nb,
                 param_grid=params_NB,
                 cv=4,
                 verbose=1,
                 scoring='accuracy')
score(gs_NB,'GaussianNB with hyperparameter tuning')

Accuracy for GaussianNB without hyperparameter tuning : 0.63935 

Fitting 4 folds for each of 100 candidates, totalling 400 fits
Accuracy for GaussianNB with hyperparameter tuning : 0.7109 



array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
knn = KNeighborsClassifier(n_neighbors=6)
score(knn,'KNeighborsClassifier')

Accuracy for KNeighborsClassifier : 0.60346 



array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
dtc = DecisionTreeClassifier(random_state=10)
# The model is the best at default(just with random_state value change) given the number of parameters that can be modified for DTC
score(dtc,'DecisionTreeClassifier')

Accuracy for DecisionTreeClassifier : 0.68412 



array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
dtc = DecisionTreeClassifier(criterion = 'gini',max_depth = 10,random_state=0)
score(dtc,'DecisionTreeClassifier')

Accuracy for DecisionTreeClassifier : 0.75918 



array([0, 0, 1, ..., 1, 1, 1])

In [ ]:
# xgb = XGBClassifier(n_estimators = 1000,learning_rate = 0.01)
# out_xgb = score(xgb, 'XGBClassifier')
# res_xgb = pd.DataFrame(out_xgb)
# res_xgb.to_csv('res_xgb.csv', index=False)

In [ ]:
xgb = XGBClassifier(n_estimators = 1000,learning_rate = 0.01)
xgb.fit(X,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
x_tes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Test_Data_Health.csv')

In [ ]:
x_tes = x_tes.apply(LabelEncoder().fit_transform)
x_tes = x_tes.drop(['Food preference'], axis =1)


In [ ]:
pred = xgb.predict(x_tes)

In [ ]:
res_xgb = pd.DataFrame(pred)

In [ ]:
# res_xgb.to_csv('res_xgb.csv', index=False)


In [ ]:
xgbrf = XGBRFClassifier(n_estimators = 1000,
                        learning_rate = 0.1
                        )
score(xgbrf,XGBRFClassifier)

Accuracy for <class 'xgboost.sklearn.XGBRFClassifier'> : 0.76619 



array([0, 0, 0, ..., 1, 1, 1])